-- Pick'Os · Easy HR — 50 empleados dummy (generado offline, listo para Cloud SQL Studio)
-- Ejecuta esto DESPUÉS de haber ejecutado db/schema.sql en la misma base de datos 'easyhr'.
BEGIN;
TRUNCATE TABLE employees RESTART IDENTITY CASCADE;

-- 1) Gerentes de cada área (sin gerente propio)
INSERT INTO employees (nombre, apellido_paterno, apellido_materno, fecha_nacimiento, fecha_ingreso, rol, area_id, gerente_id, email) VALUES ('Gabriela', 'González', 'Díaz', '1989-08-07', '2016-07-16', 'Gerente de RH', (SELECT id FROM areas WHERE nombre = 'Recursos Humanos'), NULL, 'gabriela.gonzález@pickos.com');
INSERT INTO employees (nombre, apellido_paterno, apellido_materno, fecha_nacimiento, fecha_ingreso, rol, area_id, gerente_id, email) VALUES ('Daniela', 'Medina', 'Romero', '1977-09-26', '2020-02-06', 'Gerente Legal', (SELECT id FROM areas WHERE nombre = 'Legal'), NULL, 'daniela.medina@pickos.com');
INSERT INTO employees (nombre, apellido_paterno, apellido_materno, fecha_nacimiento, fecha_ingreso, rol, area_id, gerente_id, email) VALUES ('Gustavo', 'Hernández', 'Delgado', '1986-05-19', '2018-05-29', 'Gerente de Contabilidad', (SELECT id FROM areas WHERE nombre = 'Contabilidad'), NULL, 'gustavo.hernández@pickos.com');
INSERT INTO employees (nombre, apellido_paterno, apellido_materno, fecha_nacimiento, fecha_ingreso, rol, area_id, gerente_id, email) VALUES ('Fernanda', 'Martínez', 'Reyes', '1984-05-18', '2016-10-13', 'Gerente de Marketing', (SELECT id FROM areas WHERE nombre = 'Marketing'), NULL, 'fernanda.martínez@pickos.com');
INSERT INTO employees (nombre, apellido_paterno, apellido_materno, fecha_nacimiento, fecha_ingreso, rol, area_id, gerente_id, email) VALUES ('Diego', 'Martínez', 'Romero', '1984-07-09', '2016-08-30', 'Gerente de Ingeniería', (SELECT id FROM areas WHERE nombre = 'Ingenieria'), NULL, 'diego.martínez@pickos.com');
INSERT INTO employees (nombre, apellido_paterno, apellido_materno, fecha_nacimiento, fecha_ingreso, rol, area_id, gerente_id, email) VALUES ('Patricia', 'López', 'Sánchez', '1989-02-22', '2016-09-10', 'Gerente de PMO', (SELECT id FROM areas WHERE nombre = 'PMO'), NULL, 'patricia.lópez@pickos.com');
INSERT INTO employees (nombre, apellido_paterno, apellido_materno, fecha_nacimiento, fecha_ingreso, rol, area_id, gerente_id, email) VALUES ('Patricia', 'Torres', 'Díaz', '1976-02-11', '2018-06-24', 'Gerente de Calidad', (SELECT id FROM areas WHERE nombre = 'Calidad'), NULL, 'patricia.torres@pickos.com');
INSERT INTO employees (nombre, apellido_paterno, apellido_materno, fecha_nacimiento, fecha_ingreso, rol, area_id, gerente_id, email) VALUES ('Fernanda', 'Romero', 'Aguilar', '1977-12-26', '2019-04-01', 'Gerente de Ventas', (SELECT id FROM areas WHERE nombre = 'Ventas'), NULL, 'fernanda.romero@pickos.com');

-- 2) Resto de empleados, asignados al gerente de su misma área
INSERT INTO employees (nombre, apellido_paterno, apellido_materno, fecha_nacimiento, fecha_ingreso, rol, area_id, gerente_id, email) VALUES ('Ricardo', 'Romero', 'López', '1997-09-25', '2022-06-17', 'Especialista en Procesos', (SELECT id FROM areas WHERE nombre = 'Calidad'), (SELECT id FROM employees WHERE email = (SELECT MIN(email) FROM employees e2 JOIN areas a2 ON a2.id = e2.area_id WHERE a2.nombre = 'Calidad' AND e2.gerente_id IS NULL)), 'ricardo.romero@pickos.com');
INSERT INTO employees (nombre, apellido_paterno, apellido_materno, fecha_nacimiento, fecha_ingreso, rol, area_id, gerente_id, email) VALUES ('Andrea', 'Torres', 'Torres', '1999-09-27', '2021-02-08', 'Contador Senior', (SELECT id FROM areas WHERE nombre = 'Contabilidad'), (SELECT id FROM employees WHERE email = (SELECT MIN(email) FROM employees e2 JOIN areas a2 ON a2.id = e2.area_id WHERE a2.nombre = 'Contabilidad' AND e2.gerente_id IS NULL)), 'andrea.torres@pickos.com');
INSERT INTO employees (nombre, apellido_paterno, apellido_materno, fecha_nacimiento, fecha_ingreso, rol, area_id, gerente_id, email) VALUES ('Arturo', 'Castillo', 'Martínez', '1997-09-23', '2019-09-02', 'Especialista en Licitaciones', (SELECT id FROM areas WHERE nombre = 'Legal'), (SELECT id FROM employees WHERE email = (SELECT MIN(email) FROM employees e2 JOIN areas a2 ON a2.id = e2.area_id WHERE a2.nombre = 'Legal' AND e2.gerente_id IS NULL)), 'arturo.castillo@pickos.com');
INSERT INTO employees (nombre, apellido_paterno, apellido_materno, fecha_nacimiento, fecha_ingreso, rol, area_id, gerente_id, email) VALUES ('Emilio', 'Vázquez', 'Romero', '1994-08-04', '2022-07-10', 'Especialista en Marketing Digital', (SELECT id FROM areas WHERE nombre = 'Marketing'), (SELECT id FROM employees WHERE email = (SELECT MIN(email) FROM employees e2 JOIN areas a2 ON a2.id = e2.area_id WHERE a2.nombre = 'Marketing' AND e2.gerente_id IS NULL)), 'emilio.vázquez@pickos.com');
INSERT INTO employees (nombre, apellido_paterno, apellido_materno, fecha_nacimiento, fecha_ingreso, rol, area_id, gerente_id, email) VALUES ('Raúl', 'Cruz', 'Sánchez', '2002-10-26', '2021-01-06', 'Especialista en Licitaciones Públicas', (SELECT id FROM areas WHERE nombre = 'Ventas'), (SELECT id FROM employees WHERE email = (SELECT MIN(email) FROM employees e2 JOIN areas a2 ON a2.id = e2.area_id WHERE a2.nombre = 'Ventas' AND e2.gerente_id IS NULL)), 'raúl.cruz@pickos.com');
INSERT INTO employees (nombre, apellido_paterno, apellido_materno, fecha_nacimiento, fecha_ingreso, rol, area_id, gerente_id, email) VALUES ('José', 'Torres', 'Cruz', '1996-10-12', '2024-07-20', 'Especialista en Marketing Digital', (SELECT id FROM areas WHERE nombre = 'Marketing'), (SELECT id FROM employees WHERE email = (SELECT MIN(email) FROM employees e2 JOIN areas a2 ON a2.id = e2.area_id WHERE a2.nombre = 'Marketing' AND e2.gerente_id IS NULL)), 'josé.torres@pickos.com');
INSERT INTO employees (nombre, apellido_paterno, apellido_materno, fecha_nacimiento, fecha_ingreso, rol, area_id, gerente_id, email) VALUES ('Renata', 'Ruiz', 'Martínez', '1987-08-26', '2024-09-27', 'Account Manager', (SELECT id FROM areas WHERE nombre = 'Ventas'), (SELECT id FROM employees WHERE email = (SELECT MIN(email) FROM employees e2 JOIN areas a2 ON a2.id = e2.area_id WHERE a2.nombre = 'Ventas' AND e2.gerente_id IS NULL)), 'renata.ruiz@pickos.com');
INSERT INTO employees (nombre, apellido_paterno, apellido_materno, fecha_nacimiento, fecha_ingreso, rol, area_id, gerente_id, email) VALUES ('Rosa', 'Flores', 'González', '1995-12-20', '2023-09-24', 'Contador Junior', (SELECT id FROM areas WHERE nombre = 'Contabilidad'), (SELECT id FROM employees WHERE email = (SELECT MIN(email) FROM employees e2 JOIN areas a2 ON a2.id = e2.area_id WHERE a2.nombre = 'Contabilidad' AND e2.gerente_id IS NULL)), 'rosa.flores@pickos.com');
INSERT INTO employees (nombre, apellido_paterno, apellido_materno, fecha_nacimiento, fecha_ingreso, rol, area_id, gerente_id, email) VALUES ('Rosa', 'Romero', 'Torres', '2002-09-13', '2022-07-09', 'Paralegal', (SELECT id FROM areas WHERE nombre = 'Legal'), (SELECT id FROM employees WHERE email = (SELECT MIN(email) FROM employees e2 JOIN areas a2 ON a2.id = e2.area_id WHERE a2.nombre = 'Legal' AND e2.gerente_id IS NULL)), 'rosa.romero@pickos.com');
INSERT INTO employees (nombre, apellido_paterno, apellido_materno, fecha_nacimiento, fecha_ingreso, rol, area_id, gerente_id, email) VALUES ('Verónica', 'Jiménez', 'Torres', '2002-11-16', '2024-02-12', 'Coordinador de Proyectos', (SELECT id FROM areas WHERE nombre = 'PMO'), (SELECT id FROM employees WHERE email = (SELECT MIN(email) FROM employees e2 JOIN areas a2 ON a2.id = e2.area_id WHERE a2.nombre = 'PMO' AND e2.gerente_id IS NULL)), 'verónica.jiménez@pickos.com');
INSERT INTO employees (nombre, apellido_paterno, apellido_materno, fecha_nacimiento, fecha_ingreso, rol, area_id, gerente_id, email) VALUES ('Eduardo', 'Jiménez', 'Castillo', '1999-11-24', '2019-09-24', 'Abogado Corporativo', (SELECT id FROM areas WHERE nombre = 'Legal'), (SELECT id FROM employees WHERE email = (SELECT MIN(email) FROM employees e2 JOIN areas a2 ON a2.id = e2.area_id WHERE a2.nombre = 'Legal' AND e2.gerente_id IS NULL)), 'eduardo.jiménez@pickos.com');
INSERT INTO employees (nombre, apellido_paterno, apellido_materno, fecha_nacimiento, fecha_ingreso, rol, area_id, gerente_id, email) VALUES ('Enrique', 'Torres', 'Vázquez', '1994-12-30', '2022-03-11', 'Arquitecto de Infraestructura', (SELECT id FROM areas WHERE nombre = 'Ingenieria'), (SELECT id FROM employees WHERE email = (SELECT MIN(email) FROM employees e2 JOIN areas a2 ON a2.id = e2.area_id WHERE a2.nombre = 'Ingenieria' AND e2.gerente_id IS NULL)), 'enrique.torres@pickos.com');
INSERT INTO employees (nombre, apellido_paterno, apellido_materno, fecha_nacimiento, fecha_ingreso, rol, area_id, gerente_id, email) VALUES ('Luis', 'Morales', 'Gómez', '1988-10-08', '2025-11-07', 'Coordinador de Proyectos', (SELECT id FROM areas WHERE nombre = 'PMO'), (SELECT id FROM employees WHERE email = (SELECT MIN(email) FROM employees e2 JOIN areas a2 ON a2.id = e2.area_id WHERE a2.nombre = 'PMO' AND e2.gerente_id IS NULL)), 'luis.morales@pickos.com');
INSERT INTO employees (nombre, apellido_paterno, apellido_materno, fecha_nacimiento, fecha_ingreso, rol, area_id, gerente_id, email) VALUES ('Carlos', 'Rodríguez', 'Rubio', '1991-06-13', '2020-06-13', 'Especialista en Licitaciones Públicas', (SELECT id FROM areas WHERE nombre = 'Ventas'), (SELECT id FROM employees WHERE email = (SELECT MIN(email) FROM employees e2 JOIN areas a2 ON a2.id = e2.area_id WHERE a2.nombre = 'Ventas' AND e2.gerente_id IS NULL)), 'carlos.rodríguez@pickos.com');
INSERT INTO employees (nombre, apellido_paterno, apellido_materno, fecha_nacimiento, fecha_ingreso, rol, area_id, gerente_id, email) VALUES ('Sergio', 'Díaz', 'Delgado', '1996-02-20', '2019-11-27', 'Diseñador Gráfico', (SELECT id FROM areas WHERE nombre = 'Marketing'), (SELECT id FROM employees WHERE email = (SELECT MIN(email) FROM employees e2 JOIN areas a2 ON a2.id = e2.area_id WHERE a2.nombre = 'Marketing' AND e2.gerente_id IS NULL)), 'sergio.díaz@pickos.com');
INSERT INTO employees (nombre, apellido_paterno, apellido_materno, fecha_nacimiento, fecha_ingreso, rol, area_id, gerente_id, email) VALUES ('Sergio', 'Romero', 'Ramírez', '1988-01-27', '2023-10-30', 'Especialista en Licitaciones Públicas', (SELECT id FROM areas WHERE nombre = 'Ventas'), (SELECT id FROM employees WHERE email = (SELECT MIN(email) FROM employees e2 JOIN areas a2 ON a2.id = e2.area_id WHERE a2.nombre = 'Ventas' AND e2.gerente_id IS NULL)), 'sergio.romero@pickos.com');
INSERT INTO employees (nombre, apellido_paterno, apellido_materno, fecha_nacimiento, fecha_ingreso, rol, area_id, gerente_id, email) VALUES ('Alberto', 'Reyes', 'Gómez', '2000-04-24', '2023-04-08', 'Ingeniero de Redes', (SELECT id FROM areas WHERE nombre = 'Ingenieria'), (SELECT id FROM employees WHERE email = (SELECT MIN(email) FROM employees e2 JOIN areas a2 ON a2.id = e2.area_id WHERE a2.nombre = 'Ingenieria' AND e2.gerente_id IS NULL)), 'alberto.reyes@pickos.com');
INSERT INTO employees (nombre, apellido_paterno, apellido_materno, fecha_nacimiento, fecha_ingreso, rol, area_id, gerente_id, email) VALUES ('José', 'Pérez', 'González', '1990-03-16', '2026-05-21', 'Contador Junior', (SELECT id FROM areas WHERE nombre = 'Contabilidad'), (SELECT id FROM employees WHERE email = (SELECT MIN(email) FROM employees e2 JOIN areas a2 ON a2.id = e2.area_id WHERE a2.nombre = 'Contabilidad' AND e2.gerente_id IS NULL)), 'josé.pérez@pickos.com');
INSERT INTO employees (nombre, apellido_paterno, apellido_materno, fecha_nacimiento, fecha_ingreso, rol, area_id, gerente_id, email) VALUES ('Emilio', 'Medina', 'Torres', '1989-02-02', '2021-12-12', 'Reclutador', (SELECT id FROM areas WHERE nombre = 'Recursos Humanos'), (SELECT id FROM employees WHERE email = (SELECT MIN(email) FROM employees e2 JOIN areas a2 ON a2.id = e2.area_id WHERE a2.nombre = 'Recursos Humanos' AND e2.gerente_id IS NULL)), 'emilio.medina@pickos.com');
INSERT INTO employees (nombre, apellido_paterno, apellido_materno, fecha_nacimiento, fecha_ingreso, rol, area_id, gerente_id, email) VALUES ('Ricardo', 'Reyes', 'Romero', '1993-04-13', '2025-11-02', 'Coordinador de Nómina', (SELECT id FROM areas WHERE nombre = 'Recursos Humanos'), (SELECT id FROM employees WHERE email = (SELECT MIN(email) FROM employees e2 JOIN areas a2 ON a2.id = e2.area_id WHERE a2.nombre = 'Recursos Humanos' AND e2.gerente_id IS NULL)), 'ricardo.reyes@pickos.com');
INSERT INTO employees (nombre, apellido_paterno, apellido_materno, fecha_nacimiento, fecha_ingreso, rol, area_id, gerente_id, email) VALUES ('Paulina', 'Castillo', 'Aguilar', '1996-07-24', '2025-12-04', 'Scrum Master', (SELECT id FROM areas WHERE nombre = 'PMO'), (SELECT id FROM employees WHERE email = (SELECT MIN(email) FROM employees e2 JOIN areas a2 ON a2.id = e2.area_id WHERE a2.nombre = 'PMO' AND e2.gerente_id IS NULL)), 'paulina.castillo@pickos.com');
INSERT INTO employees (nombre, apellido_paterno, apellido_materno, fecha_nacimiento, fecha_ingreso, rol, area_id, gerente_id, email) VALUES ('Fabián', 'Vargas', 'Aguilar', '2002-06-30', '2026-08-19', 'Coordinador de Nómina', (SELECT id FROM areas WHERE nombre = 'Recursos Humanos'), (SELECT id FROM employees WHERE email = (SELECT MIN(email) FROM employees e2 JOIN areas a2 ON a2.id = e2.area_id WHERE a2.nombre = 'Recursos Humanos' AND e2.gerente_id IS NULL)), 'fabián.vargas@pickos.com');
INSERT INTO employees (nombre, apellido_paterno, apellido_materno, fecha_nacimiento, fecha_ingreso, rol, area_id, gerente_id, email) VALUES ('Sergio', 'Díaz', 'Díaz', '1987-04-29', '2024-05-26', 'Especialista en Procesos', (SELECT id FROM areas WHERE nombre = 'Calidad'), (SELECT id FROM employees WHERE email = (SELECT MIN(email) FROM employees e2 JOIN areas a2 ON a2.id = e2.area_id WHERE a2.nombre = 'Calidad' AND e2.gerente_id IS NULL)), 'sergio.díaz2@pickos.com');
INSERT INTO employees (nombre, apellido_paterno, apellido_materno, fecha_nacimiento, fecha_ingreso, rol, area_id, gerente_id, email) VALUES ('Carlos', 'Rodríguez', 'Martínez', '1989-09-07', '2023-12-10', 'Analista de Calidad', (SELECT id FROM areas WHERE nombre = 'Calidad'), (SELECT id FROM employees WHERE email = (SELECT MIN(email) FROM employees e2 JOIN areas a2 ON a2.id = e2.area_id WHERE a2.nombre = 'Calidad' AND e2.gerente_id IS NULL)), 'carlos.rodríguez2@pickos.com');
INSERT INTO employees (nombre, apellido_paterno, apellido_materno, fecha_nacimiento, fecha_ingreso, rol, area_id, gerente_id, email) VALUES ('Héctor', 'Ruiz', 'Hernández', '1987-04-19', '2019-01-01', 'Especialista en Licitaciones', (SELECT id FROM areas WHERE nombre = 'Legal'), (SELECT id FROM employees WHERE email = (SELECT MIN(email) FROM employees e2 JOIN areas a2 ON a2.id = e2.area_id WHERE a2.nombre = 'Legal' AND e2.gerente_id IS NULL)), 'héctor.ruiz@pickos.com');
INSERT INTO employees (nombre, apellido_paterno, apellido_materno, fecha_nacimiento, fecha_ingreso, rol, area_id, gerente_id, email) VALUES ('Yolanda', 'López', 'Gómez', '1998-10-07', '2019-04-15', 'Contador Junior', (SELECT id FROM areas WHERE nombre = 'Contabilidad'), (SELECT id FROM employees WHERE email = (SELECT MIN(email) FROM employees e2 JOIN areas a2 ON a2.id = e2.area_id WHERE a2.nombre = 'Contabilidad' AND e2.gerente_id IS NULL)), 'yolanda.lópez@pickos.com');
INSERT INTO employees (nombre, apellido_paterno, apellido_materno, fecha_nacimiento, fecha_ingreso, rol, area_id, gerente_id, email) VALUES ('Óscar', 'Díaz', 'González', '1999-03-26', '2021-10-30', 'Especialista en Marketing Digital', (SELECT id FROM areas WHERE nombre = 'Marketing'), (SELECT id FROM employees WHERE email = (SELECT MIN(email) FROM employees e2 JOIN areas a2 ON a2.id = e2.area_id WHERE a2.nombre = 'Marketing' AND e2.gerente_id IS NULL)), 'óscar.díaz@pickos.com');
INSERT INTO employees (nombre, apellido_paterno, apellido_materno, fecha_nacimiento, fecha_ingreso, rol, area_id, gerente_id, email) VALUES ('Cynthia', 'López', 'López', '1995-12-13', '2024-03-23', 'Project Manager', (SELECT id FROM areas WHERE nombre = 'PMO'), (SELECT id FROM employees WHERE email = (SELECT MIN(email) FROM employees e2 JOIN areas a2 ON a2.id = e2.area_id WHERE a2.nombre = 'PMO' AND e2.gerente_id IS NULL)), 'cynthia.lópez@pickos.com');
INSERT INTO employees (nombre, apellido_paterno, apellido_materno, fecha_nacimiento, fecha_ingreso, rol, area_id, gerente_id, email) VALUES ('Iván', 'Martínez', 'González', '1987-04-18', '2022-11-04', 'Especialista en Licitaciones Públicas', (SELECT id FROM areas WHERE nombre = 'Ventas'), (SELECT id FROM employees WHERE email = (SELECT MIN(email) FROM employees e2 JOIN areas a2 ON a2.id = e2.area_id WHERE a2.nombre = 'Ventas' AND e2.gerente_id IS NULL)), 'iván.martínez@pickos.com');
INSERT INTO employees (nombre, apellido_paterno, apellido_materno, fecha_nacimiento, fecha_ingreso, rol, area_id, gerente_id, email) VALUES ('Cynthia', 'Medina', 'Castillo', '1988-09-28', '2024-10-15', 'Ingeniero de Data Center', (SELECT id FROM areas WHERE nombre = 'Ingenieria'), (SELECT id FROM employees WHERE email = (SELECT MIN(email) FROM employees e2 JOIN areas a2 ON a2.id = e2.area_id WHERE a2.nombre = 'Ingenieria' AND e2.gerente_id IS NULL)), 'cynthia.medina@pickos.com');
INSERT INTO employees (nombre, apellido_paterno, apellido_materno, fecha_nacimiento, fecha_ingreso, rol, area_id, gerente_id, email) VALUES ('Rodrigo', 'Gómez', 'González', '2000-06-24', '2025-02-02', 'Diseñador Gráfico', (SELECT id FROM areas WHERE nombre = 'Marketing'), (SELECT id FROM employees WHERE email = (SELECT MIN(email) FROM employees e2 JOIN areas a2 ON a2.id = e2.area_id WHERE a2.nombre = 'Marketing' AND e2.gerente_id IS NULL)), 'rodrigo.gómez@pickos.com');
INSERT INTO employees (nombre, apellido_paterno, apellido_materno, fecha_nacimiento, fecha_ingreso, rol, area_id, gerente_id, email) VALUES ('Enrique', 'Aguilar', 'Martínez', '2000-08-13', '2021-12-05', 'DevOps Engineer', (SELECT id FROM areas WHERE nombre = 'Ingenieria'), (SELECT id FROM employees WHERE email = (SELECT MIN(email) FROM employees e2 JOIN areas a2 ON a2.id = e2.area_id WHERE a2.nombre = 'Ingenieria' AND e2.gerente_id IS NULL)), 'enrique.aguilar@pickos.com');
INSERT INTO employees (nombre, apellido_paterno, apellido_materno, fecha_nacimiento, fecha_ingreso, rol, area_id, gerente_id, email) VALUES ('Ximena', 'Rubio', 'Sánchez', '1996-12-11', '2025-01-27', 'Analista Fiscal', (SELECT id FROM areas WHERE nombre = 'Contabilidad'), (SELECT id FROM employees WHERE email = (SELECT MIN(email) FROM employees e2 JOIN areas a2 ON a2.id = e2.area_id WHERE a2.nombre = 'Contabilidad' AND e2.gerente_id IS NULL)), 'ximena.rubio@pickos.com');
INSERT INTO employees (nombre, apellido_paterno, apellido_materno, fecha_nacimiento, fecha_ingreso, rol, area_id, gerente_id, email) VALUES ('Lorena', 'Sánchez', 'Ruiz', '2002-09-07', '2021-03-10', 'Coordinador de Proyectos', (SELECT id FROM areas WHERE nombre = 'PMO'), (SELECT id FROM employees WHERE email = (SELECT MIN(email) FROM employees e2 JOIN areas a2 ON a2.id = e2.area_id WHERE a2.nombre = 'PMO' AND e2.gerente_id IS NULL)), 'lorena.sánchez@pickos.com');
INSERT INTO employees (nombre, apellido_paterno, apellido_materno, fecha_nacimiento, fecha_ingreso, rol, area_id, gerente_id, email) VALUES ('Manuel', 'Guerrero', 'Sánchez', '1989-06-26', '2024-10-21', 'Auditor ISO', (SELECT id FROM areas WHERE nombre = 'Calidad'), (SELECT id FROM employees WHERE email = (SELECT MIN(email) FROM employees e2 JOIN areas a2 ON a2.id = e2.area_id WHERE a2.nombre = 'Calidad' AND e2.gerente_id IS NULL)), 'manuel.guerrero@pickos.com');
INSERT INTO employees (nombre, apellido_paterno, apellido_materno, fecha_nacimiento, fecha_ingreso, rol, area_id, gerente_id, email) VALUES ('Beatriz', 'García', 'García', '2002-09-21', '2022-02-18', 'Project Manager', (SELECT id FROM areas WHERE nombre = 'PMO'), (SELECT id FROM employees WHERE email = (SELECT MIN(email) FROM employees e2 JOIN areas a2 ON a2.id = e2.area_id WHERE a2.nombre = 'PMO' AND e2.gerente_id IS NULL)), 'beatriz.garcía@pickos.com');
INSERT INTO employees (nombre, apellido_paterno, apellido_materno, fecha_nacimiento, fecha_ingreso, rol, area_id, gerente_id, email) VALUES ('Sofía', 'Castillo', 'Ruiz', '1992-09-21', '2024-01-06', 'DevOps Engineer', (SELECT id FROM areas WHERE nombre = 'Ingenieria'), (SELECT id FROM employees WHERE email = (SELECT MIN(email) FROM employees e2 JOIN areas a2 ON a2.id = e2.area_id WHERE a2.nombre = 'Ingenieria' AND e2.gerente_id IS NULL)), 'sofía.castillo@pickos.com');
INSERT INTO employees (nombre, apellido_paterno, apellido_materno, fecha_nacimiento, fecha_ingreso, rol, area_id, gerente_id, email) VALUES ('José', 'Sánchez', 'López', '1990-02-02', '2024-04-09', 'Coordinador de Proyectos', (SELECT id FROM areas WHERE nombre = 'PMO'), (SELECT id FROM employees WHERE email = (SELECT MIN(email) FROM employees e2 JOIN areas a2 ON a2.id = e2.area_id WHERE a2.nombre = 'PMO' AND e2.gerente_id IS NULL)), 'josé.sánchez@pickos.com');
INSERT INTO employees (nombre, apellido_paterno, apellido_materno, fecha_nacimiento, fecha_ingreso, rol, area_id, gerente_id, email) VALUES ('Roberto', 'Jiménez', 'Ruiz', '1998-09-09', '2019-01-08', 'Project Manager', (SELECT id FROM areas WHERE nombre = 'PMO'), (SELECT id FROM employees WHERE email = (SELECT MIN(email) FROM employees e2 JOIN areas a2 ON a2.id = e2.area_id WHERE a2.nombre = 'PMO' AND e2.gerente_id IS NULL)), 'roberto.jiménez@pickos.com');
INSERT INTO employees (nombre, apellido_paterno, apellido_materno, fecha_nacimiento, fecha_ingreso, rol, area_id, gerente_id, email) VALUES ('Enrique', 'Martínez', 'Medina', '1999-10-26', '2020-05-06', 'Project Manager', (SELECT id FROM areas WHERE nombre = 'PMO'), (SELECT id FROM employees WHERE email = (SELECT MIN(email) FROM employees e2 JOIN areas a2 ON a2.id = e2.area_id WHERE a2.nombre = 'PMO' AND e2.gerente_id IS NULL)), 'enrique.martínez@pickos.com');
INSERT INTO employees (nombre, apellido_paterno, apellido_materno, fecha_nacimiento, fecha_ingreso, rol, area_id, gerente_id, email) VALUES ('Cynthia', 'Vargas', 'Pérez', '1994-09-25', '2026-02-17', 'Especialista en Marketing Digital', (SELECT id FROM areas WHERE nombre = 'Marketing'), (SELECT id FROM employees WHERE email = (SELECT MIN(email) FROM employees e2 JOIN areas a2 ON a2.id = e2.area_id WHERE a2.nombre = 'Marketing' AND e2.gerente_id IS NULL)), 'cynthia.vargas@pickos.com');
INSERT INTO employees (nombre, apellido_paterno, apellido_materno, fecha_nacimiento, fecha_ingreso, rol, area_id, gerente_id, email) VALUES ('Beatriz', 'Díaz', 'Morales', '1994-09-24', '2019-12-14', 'Especialista en Licitaciones', (SELECT id FROM areas WHERE nombre = 'Legal'), (SELECT id FROM employees WHERE email = (SELECT MIN(email) FROM employees e2 JOIN areas a2 ON a2.id = e2.area_id WHERE a2.nombre = 'Legal' AND e2.gerente_id IS NULL)), 'beatriz.díaz@pickos.com');

COMMIT;